### ISSUE TITLE
React displays type error when input field is empty

### ISSUE THREAD

**Issue by SnGrimes** [chingu-voyage4/Geckos-Team-0#13]
@abecel22  
![empty label error](https://user-images.githubusercontent.com/14166723/37372752-e2105c82-26e1-11e8-9dc9-66ab7a65bb3f.png)
I pulled the changes to test the new changes and this issue has popped up. If I have already added an ingredient to the list and then delete the input field to type in a new ingredient React will display the attached error. I'm going to start playing with it and see if maybe setting a default value to label will prevent this error from throwing.

**Comment by SnGrimes** [comment]
Created a fix by adding the code below to `ingredientSelection(data)` in searchBar.js. I will work on a better fix that doesn't use alert();
```
if (data === null) {
     alert('Enter an ingredient');
} else {
     this.props.ingredientSelection(data);
  }

**Comment by abecel22** [comment]
Added a PR to fix issue.
