### ISSUE TITLE
Tweak searchBar logic so that search can be performed without selecting autocomplete results

### ISSUE THREAD

**Issue by SnGrimes** [chingu-voyage4/Geckos-Team-0#46]
**_Issue Description & Expected Outcome:_** 
One of the options available from autocomplete has to be selected before an ingredient can be added to the ingredient list. The searchBar component's logic needs to be revised, so that a search can be completed even if the ingredient was just typed into the text field.

**_Symptoms:_**
Unable to perform ingredient search unless an autocomplete item has been selected. A value that has been typed into the text field will not be accepted for the API call.

**_Steps to Recreate:_** 
Happens every time you try to add an ingredient to the ingredient list

**_Resolution:_**

**Comment by SnGrimes** [comment]
Could use an OR statement to allow the search to proceed if there is at least a value in the text field.

**Comment by SDBowen** [comment]
Fixed this with PR #59
