### ISSUE TITLE
Add hover styles when user tabs to the Add button

### ISSUE THREAD

**Issue by SnGrimes** [chingu-voyage4/Geckos-Team-0#48]
*_Issue Description & Expected Outcome:_** 
When the user tabs to the Add button, there isn't any visual indication that the Add button has focus. Need to add CSS styles that indicate that the Add button has focus.

**_Symptoms:_**
No visual indication that Add button has focus if using only keyboard to navigate the interface.

**_Steps to Recreate:_** 
Enter an ingredient and hit tab

**_Resolution:_**

**Comment by abecel22** [comment]
Fixed in PR #53
