### ISSUE TITLE
Add ability to click screen to close BMI modal

### ISSUE THREAD

**Issue by SnGrimes** [chingu-voyage4/Geckos-Team-0#49]
**_Issue Description & Expected Outcome:_** 
The only way to close the BMI calculator modal is to click the BMI calculator button again. Would like the ability for the user to close the modal when something other than the modal is clicked.
**_Symptoms:_**
Can only close BMI calculator modal by clicking the BMI calculator button in the hamburger menu
**_Steps to Recreate:_** 
Click the BMI calculator button under the hamburger menu
**_Resolution:_**

**Comment by SDBowen** [comment]
Pull request #54 adds this ability.
