### ISSUE TITLE
Duplicate ingredients can be added to the ingredient list.

### ISSUE THREAD

**Issue by SDBowen** [chingu-voyage4/Geckos-Team-0#60]
Issue Description & Expected Outcome:
User can add the same ingredient multiple times by adding space(s) to the end of their ingredient name in the search bar. This should result in a existing ingredient warning.

Symptoms:
Duplicate ingredients in the ingredient list.

Steps to Recreate:
Add ingredient, then add second ingredient, with the same name, but include a space (" ") at the end.

**Comment by SnGrimes** [comment]
.trim() will clean that up real fast. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by SDBowen** [comment]
trim() did it! #66
