### ISSUE TITLE
Nutrition table overlaps the form div.

### ISSUE THREAD

**Issue by abecel22** [chingu-voyage4/Geckos-Team-0#63]
Issue Description & Expected Outcome:
When user adds one ingredient to list, the nutrition table overlaps the form div. The table should not overlap and will need margin. 

Symptoms:
Overlaps over form. 

Steps to Recreate:
Search an ingredient, and add to the list. The table will appear. 
![screen shot 2018-04-11 at 9 46 26 pm](https://user-images.githubusercontent.com/25330153/38653843-4caa3912-3dd2-11e8-8b1a-00b004c19b16.png)

**Comment by SnGrimes** [comment]
Oops, thought I checked that before push to remote. I'll fix it.

**Comment by SnGrimes** [comment]
Fixed in #64
